Feature happy shellcheck (#5)
* Enough for one day. skipped: 0 failed: 52 passed: 15

* skipped: 0 failed: 42 passed: 25

* skipped: 0 failed: 25 passed: 42

* skipped: 0 failed: 0 passed: 67

* Bumped version

diff --git a/files/build/bin/svnwinx b/files/build/bin/svnwinx
--- a/files/build/bin/svnwinx
+++ b/files/build/bin/svnwinx
@@ -1,23 +1,32 @@
 #!/bin/bash
-# -*- Mode: Bash; tab-width: 2; indent-tabs-mode: nil -*- vim:sta:et:sw=2:ts=2:syntax=sh#
+# vim:sta:et:sw=2:ts=2:syntax=sh
 # Dependencies:
 #  svnwin
 #
 # Revision History
-#  20150510 - richarjt - initial version
+# 20150510 - que - initial version
+# 20210101 - que - shellcheck corrections
 #
 
+SCRIPT=$(basename "$0")
 SCRDIR=$(dirname "$0")
+ERRORS=0
 
-if [ -f "$1" ]; then
-  while [ -f "$1" ]
+if [ -n "$1" ]
+then
+  while [ -n "$1" ]
   do
-    ${SCRDIR}/svnwin -x "$1"
-#    svn propset svn:keywords "Id Author Date HeadURL Revision" "$1"
-#    svn propset svn:eol-style LF "$1"
-#    svn propset svn:executable '' "$1"
+    if [ -f "$1" ]
+    then
+      "${SCRDIR}"/svnwin -x "$1" || ((ERRORS+=1))
+    else
+      echo "File not found: $1"
+    fi
     shift
   done
 else
-  echo "File not found: $1"
+  echo "usage: $SCRIPT file [ file1 ... ]"
+  ((ERRORS+=1))
 fi
+
+exit "$ERRORS"
